# Classification and Regression, Part 1

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sktime.datasets import load_UCR_UEA_dataset

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dask/dataframe/_pyarrow_compat.py:23: UserWarning: You are using pyarrow version 11.0.0 which is known to be insecure. See https://www.cve.org/CVERecord?id=CVE-2023-47248 for further details. Please upgrade to pyarrow>=14.0.1 or install pyarrow-hotfix to patch your current version.
  warnings.warn(


In [3]:
X_train, y_train = load_UCR_UEA_dataset("Computers", return_type="numpy3D", split="train")
X_test, y_test = load_UCR_UEA_dataset("Computers", return_type="numpy3D", split="test")

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

In [4]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

NameError: name 'X_train' is not defined

In [114]:
# randomly add missing values to the training and test sets
np.random.seed(0)
n_train, n_steps, n_dims = X_train.shape
n_test = X_test.shape[0]
# randomly select 2% of the values to be missing
missing = np.random.choice(n_train * n_steps * n_dims, size=int(0.02 * n_train * n_steps * n_dims), replace=False)
X_train.ravel()[missing] = np.nan
missing = np.random.choice(n_test * n_steps * n_dims, size=int(0.02 * n_test * n_steps * n_dims), replace=False)
X_test.ravel()[missing] = np.nan

In [115]:
# randomly add very large values to the training and test sets
np.random.seed(0)
high_vals = np.random.choice(n_train * n_steps * n_dims, size=int(0.0001 * n_train * n_steps * n_dims), replace=False)
print(len(high_vals))
X_train.ravel()[high_vals] = np.random.randint(1e4, 1e4+100, size=len(high_vals))
high_vals = np.random.choice(n_test * n_steps * n_dims, size=int(0.00005 * n_test * n_steps * n_dims), replace=False)
X_test.ravel()[high_vals] = np.random.randint(1e4, 1e4+100, size=len(high_vals))
print(len(high_vals))


18
9


In [116]:
# randomly shift the training and test sets
np.random.seed(0)
shift = np.random.randint(0, 100, size=n_train)[:, np.newaxis, np.newaxis]-50
X_train = X_train + shift
shift = np.random.randint(0, 100, size=n_test)[:, np.newaxis, np.newaxis]-50
X_test = X_test + shift

In [117]:
# Generate a white noise signal
white_noise = np.random.normal(0, 1, 720)

# Generate a random walk signal
random_walk = np.cumsum(white_noise)

In [118]:
X_train = np.concatenate([X_train[:50], white_noise[np.newaxis, np.newaxis, :], X_train[50:]])
y_train = np.concatenate([y_train[:50], np.array([1]), y_train[50:]])

In [119]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((251, 1, 720), (251,), (250, 1, 720), (250,))

In [120]:
np.nonzero(np.isnan(X_train))

(array([  0,   0,   0, ..., 250, 250, 250]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([  5,  96, 136, ..., 528, 585, 645]))

In [121]:
# save the data
np.save("data/X_train_computers.npy", X_train)
np.save("data/y_train_computers.npy", y_train)
np.save("data/X_test_computers.npy", X_test)
np.save("data/y_test_computers.npy", y_test)